# all paths are relative to the project root directory
# rust section can be removed for C++-only project and vice-versa

[cpp]
path = "."
# compiler can be set to: gcc, clang, msvc, clang-cl
compiler = "clang"
use_ninja = true
shared_libs = false
# targets per the first argument of add_library or add_executable
targets = [ "all" ]

#[rust]
#path = "rust"

#[test]
#path = "your_test_script.py"
